api-version: 1.8
main: com.gmail.cuestamanue7.Paintball
version: 1.0
name: PaintBall
softdepend: [Multiverse-Core]
depend: [WorldEdit]

commands:
    paintball:
        description: Comando principal PaintBall